## board

In [2]:
import numpy as np

In [6]:
board = np.zeros([5,5])

In [13]:
print(board)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [17]:
moves= {'[0,0]':'[1,2]','[2,1]'}

SyntaxError: invalid syntax (<ipython-input-17-e281dc090952>, line 1)

In [16]:
moves['[0,0]']

'[1,2],[2,1]'